# Generated by Django 4.2.2 on 2023-06-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(default='', max_length='300'),
        ),
    ]
